### PR TITLE
installing github action for automatic checks

### PR DESCRIPTION
**Pull request by tuxette**

### CODE REVIEW

**Comment by zeileis** [comment]
Nathalie @tuxette, thanks for putting this together. I did some touch-ups, mostly in formatting and documentation. (Disclaimer: I didn't try to actually run the action, though.) I just wondered whether it is true that the `task-view` input still has the `required: true` specification. I thought we were able to avoid that by computing it from the repository name? But possibly I'm not understanding correctly how exactly this is processed.

Feel free to merge the PR yourself if everything is in order (and I didn't mess up anything).

**Comment by tuxette** [comment]
@zeileis :
- I did not see the `task-view` input when I ran my tests: it should be deleted (but I'll check it before I do it, not tonight though);
- I added the standard "author" field in the yml file;
- I'll merge the PR when the first point is checked. Thanks for your feedback and corrections!

**Comment by zeileis** [comment]
OK, good, thanks Nathalie @tuxette. Additionally, I think it would be fair to add "CRAN Task View Initiative" as the second author because we did a few improvements.

**Comment by tuxette** [comment]
I removed the section on the `task-view` input and retested it. I think it's OK now and I'm merging this branch.

**Comment by zeileis** [comment]
Wonderful thanks! 🎉

**Comment by tuxette** [comment]
> OK, good, thanks Nathalie @tuxette. Additionally, I think it would be fair to add "CRAN Task View Initiative" as the second author because we did a few improvements.

I forgot this remark. It's done now.

**Pull request merged**
